In [4]:
import numpy as np
import pandas as pd

In [5]:
data={
    'Name': ['Anuj','Anij',"Aastha",'Asmita','Om'],
    'Age': [20,19,np.nan,np.nan,24],
    'Salary': [50000,60000,70000,np.nan,np.nan]
}

df=pd.DataFrame(data)
df

     Name   Age   Salary
0    Anuj  20.0  50000.0
1    Anij  19.0  60000.0
2  Aastha   NaN  70000.0
3  Asmita   NaN      NaN
4      Om  24.0      NaN

In [6]:
df.isnull().sum()

Name      0
Age       2
Salary    2
dtype: int64

In [7]:
df.dropna()

   Name   Age   Salary
0  Anuj  20.0  50000.0
1  Anij  19.0  60000.0

In [8]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)
df

C:\Users\anujs\AppData\Local\Temp\ipykernel_13400\4170140246.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
C:\Users\anujs\AppData\Local\Temp\ipykernel_13400\4170140246.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

     Name   Age   Salary
0    Anuj  20.0  50000.0
1    Anij  19.0  60000.0
2  Aastha  21.0  70000.0
3  Asmita  21.0  60000.0
4      Om  24.0  60000.0

In [9]:
df.isnull().mean()*100

Name      0.0
Age       0.0
Salary    0.0
dtype: float64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
data=pd.read_csv("Employee.csv")
df=pd.DataFrame(data)
df

      Education  JoiningYear  ... ExperienceInCurrentDomain  LeaveOrNot
0     Bachelors         2017  ...                         0           0
1     Bachelors         2013  ...                         3           1
2     Bachelors         2014  ...                         2           0
3       Masters         2016  ...                         5           1
4       Masters         2017  ...                         2           1
...         ...          ...  ...                       ...         ...
4648  Bachelors         2013  ...                         4           0
4649    Masters         2013  ...                         2           1
4650    Masters         2018  ...                         5           1
4651  Bachelors         2012  ...                         2           0
4652  Bachelors         2015  ...                         4           0

[4653 rows x 9 columns]

In [12]:
dfLabel=df.copy()

In [13]:
le=LabelEncoder()
dfLabel['Gender_Encoded']= le.fit_transform(dfLabel['Gender'])
dfLabel['EverBenched_Encoded']= le.fit_transform(dfLabel['EverBenched'])

dfLabel[['City','Gender','Gender_Encoded','EverBenched','EverBenched_Encoded']].head()

        City  Gender  Gender_Encoded EverBenched  EverBenched_Encoded
0  Bangalore    Male               1          No                    0
1       Pune  Female               0          No                    0
2  New Delhi  Female               0          No                    0
3  Bangalore    Male               1          No                    0
4       Pune    Male               1         Yes                    1

In [14]:
dfEcoded=pd.get_dummies(df,columns=['City'])
dfEcoded

      Education  JoiningYear  ...  City_New Delhi  City_Pune
0     Bachelors         2017  ...           False      False
1     Bachelors         2013  ...           False       True
2     Bachelors         2014  ...            True      False
3       Masters         2016  ...           False      False
4       Masters         2017  ...           False       True
...         ...          ...  ...             ...        ...
4648  Bachelors         2013  ...           False      False
4649    Masters         2013  ...           False       True
4650    Masters         2018  ...            True      False
4651  Bachelors         2012  ...           False      False
4652  Bachelors         2015  ...           False      False

[4653 rows x 11 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

scaler=StandardScaler()
XScaled=scaler.fit_transform()

scaler=MinMaxScaler()
XScaled=scaler.fit_transform()

In [7]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split

data={
    'studyHours':[1,2,3,4,5],
    'testScore': [40,50,60,70,80]
}

df=pd.DataFrame(data)

standardScaler=StandardScaler()
standardScaled=standardScaler.fit_transform(df)

pd.DataFrame(standardScaled,columns=['studyHours','testScore'])

scaler=MinMaxScaler()
XScaled=scaler.fit_transform(df)

pd.DataFrame(XScaled,columns=['studyHours','testScore'])

   studyHours  testScore
0        0.00       0.00
1        0.25       0.25
2        0.50       0.50
3        0.75       0.75
4        1.00       1.00

In [ ]:
X=df[['studyHours']]
y=df[['testScore']]

XTrain,XTest,yTrain,yTest=train_test_split(X,y,test_size=0.2,random_state=42)

print(yTrain)
print(yTest)

   testScore
4         80
2         60
0         40
3         70
   testScore
1         50